### ISSUE TITLE
Update the name of the repository

### ISSUE THREAD

**Issue by ParardhaKumar** [aakardwivedi/mp3app#1]
@aakardwivedi Kindly see to it

**Comment by aakardwivedi** [comment]
Any suggestions? @ParardhaKumar

**Comment by ParardhaKumar** [comment]
AI-Music-Composer

**Comment by rajat-007** [comment]
AI MusicComposer: A Machine Learning Model

**Comment by aakardwivedi** [comment]
I would rather go for MusicComposer: A Machine Learning Model.
